#include "classification_config.h" 
const classify_config mobilenetv2_config=
{
    MOBILENETV2_ONNXFILENAME,
	MOBILENETV2_BINFILENAME,
    MOBILENETV2_INPUTTENSORNAMES,
    MOBILENETV2_OUTPUTTENSORNAMES,
    MOBILENETV2_CUDAID,
    MOBILENETV2_INPUTDIM,
    MOBILENETV2_OUTPUTDIM,
    MOBILENETV2_RESIZE,
    MOBILENETV2_BATCHSIZE,
    MOBLIENETV2_meanVals,
    MOBLIENETV2_normVals,
    MOBILENETV2_CLASS_NUM,
    MOBILENETV2_TOPNUMS,
    MOBILENETV2_FP16,
    MOBILENETV2_INT8
};
