#include "classification_config.h" 
const classify_config mobilenetv2_config=
{
    MOBILENETV2_ONNXFILENAME,
	MOBILENETV2_BINFILENAME,
    MOBILENETV2_INPUTTENSORNAMES,
    MOBILENETV2_OUTPUTTENSORNAMES,
    MOBILENETV2_CUDAID,
    MOBILENETV2_RESIZE,
    MOBILENETV2_BATCHSIZE,
    MOBLIENETV2_meanVals,
    MOBLIENETV2_normVals,
    MOBILENETV2_CLASS_NUM,
    MOBILENETV2_TOPNUMS,
    MOBILENETV2_FP16,
    MOBILENETV2_INT8
};

const classify_config alexnet_config =
{
    ALEXNET_ONNXFILENAME,
	ALEXNET_BINFILENAME,
    ALEXNET_INPUTTENSORNAMES,
    ALEXNET_OUTPUTTENSORNAMES,
    ALEXNET_CUDAID,
    ALEXNET_RESIZE,
    ALEXNET_BATCHSIZE,
    ALEXNET_meanVals,
    ALEXNET_normVals,
    ALEXNET_CLASS_NUM,
    ALEXNET_TOPNUMS,
    ALEXNET_FP16,
    ALEXNET_INT8
};
